# permissions for end users to view ansibleswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleswitch-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ansibleswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ansibleswitches/status
  verbs:
  - get
