# permissions for end users to edit ansibleswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleswitch-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ansibleswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ansibleswitches/status
  verbs:
  - get
