# permissions for end users to edit ansibles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansible-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ansibles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ansibles/status
  verbs:
  - get
