# permissions for end users to view ansibles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansible-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ansibles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ansibles/status
  verbs:
  - get
