# permissions for end users to view networkconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkconfiguration-viewer-role
rules:
- apiGroups:
  - metal3.io.my.domain
  resources:
  - networkconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io.my.domain
  resources:
  - networkconfigurations/status
  verbs:
  - get
