# permissions for end users to edit networkbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkbinding-editor-role
rules:
- apiGroups:
  - metal3.io.my.domain
  resources:
  - networkbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io.my.domain
  resources:
  - networkbindings/status
  verbs:
  - get
