# permissions for end users to view networkbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkbinding-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - networkbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - networkbindings/status
  verbs:
  - get
