# permissions for end users to edit openvswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openvswitch-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - openvswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - openvswitches/status
  verbs:
  - get
