# permissions for end users to view openvswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openvswitch-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - openvswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - openvswitches/status
  verbs:
  - get
