# permissions for end users to edit ovsswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovsswitch-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ovsswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ovsswitches/status
  verbs:
  - get
