# permissions for end users to edit ports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - ports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - ports/status
  verbs:
  - get
