# permissions for end users to edit switchresourcelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchresourcelimit-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - switchresourcelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - switchresourcelimits/status
  verbs:
  - get
