# permissions for end users to view switchports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchport-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - switchports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - switchports/status
  verbs:
  - get
