# permissions for end users to view switchportconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchportconfiguration-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - switchportconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - switchportconfigurations/status
  verbs:
  - get
