# permissions for end users to view switchresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchresource-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - switchresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - switchresources/status
  verbs:
  - get
