# permissions for end users to edit switchports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchport-editor-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - switchports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - switchports/status
  verbs:
  - get
