apiVersion: metal3.io/v1alpha1
kind: Switch
metadata:
  name: switch-example
spec:
  provider:
    kind: AnsibleSwitch
    name: ansible-switch-example
  ports:
    switchport-example:
      name: <port-name>
