apiVersion: v1
kind: Secret
metadata:
  name: ansible-switch-example-secret
type: Opaque
data:
  username: <base64-host-username>
  password: <base64-host-password>

---
apiVersion: metal3.io/v1alpha1
kind: AnsibleSwitch
metadata:
  name: ansible-switch-example
spec:
  host: <host-ip>
  os: openvswitch
  bridge: <bridge-name>
  credentials:
    name: ansible-switch-example-secret
