---
apiVersion: v1
kind: Secret
metadata:
  name: switch-example-secret
type: Opaque
data:
  username: <base64-host-username>
  password: <base64-host-password>

---
apiVersion: metal3.io/v1alpha1
kind: AnsibleSwitch
metadata:
  name: ansible-switch-example
spec:
  host: <host-ip>
  os: openvswitch
  bridge: <bridge-name>
  secret:
    name: switch-example-secret
    namespace: default

---
apiVersion: metal3.io/v1alpha1
kind: Switch
metadata:
  name: switch-example
spec:
  provider:
    kind: AnsibleSwitch
    name: ansible-switch-example
  ports:
    "switchport-example":
      name: <port-name>
