@startuml state

(*) --> [ User create CR ] "<none>"

"<none>" --> "Idle"

"Idle" --> [ spec.configurationRef != nil\n (with exponential backoff)] "Configuring*"
"Idle" --> [ !instance.DeletionTimestamp.IsZero() ] "Deleting"

"Configuring*" --> [ Configuration finished ] "Active*"

"Active*" --> [ Configuration mismatch ] "Configuring*"
"Active*" --> [ spec.configurationRef is nil ] "Cleaning*"

"Cleaning*" --> [ Clean finished ] "Idle"

"Deleting" --> [ CR have been removed ] (*)

@enduml
