@startuml switch-port-state

(*) --> [ User create CR ] "<none>"

"<none>" --> "Idle"

"Idle" --> [ spec.configurationRef != nil\n (with exponential backoff)] "Validating*"
"Idle" --> [ !instance.DeletionTimestamp.IsZero() ] "Deleting"


"Validating*" --> [ spec.configurationRef is nil ||\n !instance.DeletionTimestamp.IsZero() ] "Idle"
"Validating*" --> [ The configuration meets the\n requirements of the switch ] "Configuring*"

"Configuring*" --> [ Configuration finished ] "Active*"
"Configuring*" --> [ spec.configurationRef is nil ||\n !instance.DeletionTimestamp.IsZero() ] "Cleaning*"

"Active*" --> [ Saved configuration and\n actual configuration mismatch ] "Configuring*"
"Active*" --> [ spec.configurationRef is nil ||\n !instance.DeletionTimestamp.IsZero() ] "Cleaning*"

"Cleaning*" --> [ Clean finished ] "Idle"

"Deleting" --> [ CR have been removed ] (*)

@enduml
