@startuml state

(*) --> [ User create CR ] "<none>"

"<none>" --> "Created"

"Created" --> "Configuring"
"Created" --> [ !instance.DeletionTimestamp.IsZero() ] "Deleted"
"Created" --> "Created"

"Configuring" --> "Configuring"
"Configuring" --> "Configured"

"Configured" --> [ Configuration have been updated ] "Configuring"
"Configured" --> [ Detection configuration is changed ] "Configured"
"Configured" --> [ !instance.DeletionTimestamp.IsZero() || spec.configurationRef is nil ] "Deleting"

"Deleting" --> "Deleting"
"Deleting" --> "Deleted"

"Deleted" --> [ Spec.configurationRef isn't nil ] "<none>"
"Deleted" --> [ CR have been removed ] (*)

@enduml
