@startuml state

(*) --> [ User create CR ] "<none>"

"<none>" --> "Created"

"Created" --> [ spec.configurationRef != nil ] "Configuring"
"Created" --> [ !instance.DeletionTimestamp.IsZero() ] "Cleaned"
"Created" --> [ spec.configurationRef == nil ] "Created"

"Configuring" --> [ Check configuration progress ] "Configuring"
"Configuring" --> [ Configuration finished ] "Configured"

"Configured" --> [ Configuration have been updated ] "Configuring"
"Configured" --> [ Detection whether the target configuration is\n consistent with the actual configuration ] "Configured"
"Configured" --> [ !instance.DeletionTimestamp.IsZero() || spec.configurationRef is nil ] "Cleaning"

"Cleaning" --> [ Check Clean progress ] "Cleaning"
"Cleaning" --> [ Clean finished ] "Cleaned"

"Cleaned" --> [ Spec.configurationRef isn't nil ] "<none>"
"Cleaned" --> [ CR have been removed ] (*)

@enduml
