name: CI

on:
  push:
    branchs: [master]
  pull_request:
    branchs: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: make fmt
      - name: lint
        run: make lint
      - name: vet
        run: make vet
      - name: sec
        run: make sec
      - name: unit
        run: make unit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
