name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: make fmt
      - name: lint
        run: make lint
      - name: vet
        run: make vet
      - name: sec
        run: make sec
      - name: generate
        run: make generate
      - name: manifests
        run: make manifests
      - name: unit
        run: ./hack/installKubebuilder.sh && make unit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
