name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: gofmt
        run: make gofmt
      - name: golint
        run: make golint
      - name: govet
        run: make govet
      - name: gosec
        run: make gosec
      - name: generate
        run: make generate && ./hack/gitdiff.sh
      - name: manifests
        run: make manifests && ./hack/gitdiff.sh
      - name: unit
        run: make unit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker
        run: make docker
  test-integration:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install kubernetes
        uses: helm/kind-action@v1.2.0
      - name: install CRDs
        run: make install
      - name: build image
        run: make docker
      - name: deploy controller
        run: make deploy
      - name: integration test
        run: ./hack/test_integration.sh
