name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gofmt
        run: make gofmt
      - name: golint
        run: make golint
      - name: govet
        run: make govet
      - name: gosec
        run: make gosec
      - name: generate
        run: make generate
      - name: manifests
        run: make manifests
      - name: unit
        run: ./hack/installkubebuilder.sh && make unit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
